version: '3.8'

services:
  db:
    build: ./api/docker
    ports:
        - 1433:1433
    container_name: social-db
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend: