version: '3.8'

services:
  db:
    build: ./db
    ports:
        - 1433:1433
    container_name: social-db
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - backend
  api:
    build: ./api
    ports:
        - 8080:8080
    container_name: social-api
    networks:
      - backend
  front:
    build: ./app
    ports:
      - 4200:4200
    container_name: social-web
    networks:
      - backend
    

volumes:
  db-data:

networks:
  backend: